# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"
  config.vm.network "private_network", ip: "192.168.88.10"
  config.vm.provision "shell", path: "../web-server-install.sh"
  config.vm.provision "shell", inline: <<-SHELL
    hostnamectl set-hostname node-1
  SHELL

end
