# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"
  config.vm.network "private_network", ip: "192.168.88.8"
  config.vm.provision "shell" do |s| 
    s.path = "../keepalived-install.sh"
    s.args = ["100"]
  end
  config.vm.provision "shell", inline: <<-SHELL
    hostnamectl set-hostname keepalived
  SHELL

end
